name: analyze & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze .

      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: flutter format lib/** --set-exit-if-changed

      - name: Run tests
        run: flutter test -r expanded
